#!/usr/bin/env python3

# Copyright (c) 2020 Jeffrey A. Webb

import os
from pathlib import Path
import sys

# Add the project root directory to sys.path and execute the
# hildegard.__main__ module as a script.
hildegard_root = Path(sys.path[0]) / Path("..")
cmd = f"PYTHONPATH={hildegard_root}/$PYTHONPATH python3 -m hildegard"
result = os.system(cmd)
exit_code = result >> 8
sys.exit(exit_code)
